title: Machine Learning
author: Tejas Patel
email: tjpatel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Machine learning is an application of artificial intelligence (AI) that provides systems the ability to automatically learn and improve from experience without being explicitly programmed. Machine learning focuses on the development of computer programs that can access data and use it learn for themselves.

# social links
twitter_username: tj patel
github_username:  tejasPatell

show_excerpts: true # set to false to remove excerpts on the homepage

minima: jekyll-theme-hacker 
